name: Trading Bot Live
on:
  push:
    branches: [ main, master ]  # This will trigger on any push to main or master
  workflow_dispatch:  # This allows manual triggers
    inputs:
      account_type:
        description: 'Account type (cent/standard)'
        required: true
        default: 'standard'
        type: choice
        options:
          - standard
          - cent

jobs:
  test-workflow:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Test Run
        run: |
          echo "Workflow is working!"
          echo "Selected account type: ${{ github.event.inputs.account_type || 'standard' }}"



