name: Trading Bot
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual trigger
  push:                    # Runs on every push to test setup

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EXNESS_ACCOUNT: ${{ secrets.EXNESS_ACCOUNT }}
          EXNESS_PASSWORD: ${{ secrets.EXNESS_PASSWORD }}
          EXNESS_SERVER: ${{ secrets.EXNESS_SERVER }}
        run: python scalping_bot.py --mode live --account standard
