name: Trading Bot Live
on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:
    inputs:
      account_type:
        description: 'Account type (cent/standard)'
        required: true
        default: 'standard'
        type: choice
        options:
          - standard
          - cent

permissions:
  contents: read
  actions: write

jobs:
  trading-bot:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2
      
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4.5.0
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install --no-cache-dir -r requirements.txt
          
      - name: Download MT5
        run: |
          Invoke-WebRequest -Uri "https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe" -OutFile mt5setup.exe
          
      - name: Install MT5
        run: |
          Start-Process -FilePath "mt5setup.exe" -ArgumentList "/auto" -Wait
          
      - uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e  # v2.27.0
        with:
          name: model-files
          path: .
          workflow: main.yml
          if_no_artifact_found: warn
        
      - name: Run trading bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EXNESS_ACCOUNT: ${{ secrets.EXNESS_ACCOUNT }}
          EXNESS_PASSWORD: ${{ secrets.EXNESS_PASSWORD }}
          EXNESS_SERVER: ${{ secrets.EXNESS_SERVER }}
        run: |
          python scalping_bot.py --mode live --account ${{ github.event.inputs.account_type || 'standard' }}

      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb  # v3.1.1
        if: always()
        with:
          name: model-files
          path: |
            model.pkl
            scaler.pkl
